- hosts: localhost

  tasks:
    - name: Greetings
      shell: echo Hello

    - name: Skip
      debug: msg="Hello again"
      when: False

    - name: Fail and continue
      fail: msg="What can go wrong?"
      ignore_errors: True

    - name: Fail
      fail: msg="OH Nooooo--"

