- hosts: pull
  gather_facts: no

  tasks:
  - raw: yum install -y sudo which
    args:
      creates: /bin/sudo
    register: yum_install
    changed_when: "'Nothing to do' not in yum_install.stdout"

- hosts: pull
  become: yes

  vars:
    # schedule is fed directly to cron
    schedule: '* * * * *'

    # User to run ansible-pull as from cron
    cron_user: root
    cron_group: root

    # File that ansible will use for logs
    logfile: /var/log/ansible-pull.log

    # Directory to where repository will be cloned
    workdir: /var/lib/ansible/local

    # Repository and Branch to check out
    repo_url: git://github.com/sbeliakou/ansible-examples.git
    repo_branch: develop
   
    # Playbook to apply on the host
    playbook: "trainings/day-5/tasks/pull/$(hostname -f).yml"

  tasks:
    - name: install yum-utils
      yum: name=yum-utils

    - name: install packages
      yum: name={{ item }}
      with_items:
      - epel-release
      - git
      - cronie

    - name: install python pip
      yum: name=python-pip
      
    - name: ensure cron is running
      systemd: name=crond state=started

    - name: Install ansible
      pip: name=ansible

    - name: Create local directory to work from
      file: 
        path: "{{ workdir }}"
        state: directory
        owner: "{{ cron_user }}"
        group: "{{ cron_group }}"
        mode: 0751

    - name: Create Ansible Pull Cron Job
      cron:
        name: "Ansible Pull Job"
        job: >-
          ANSIBLE_CONFIG={{ workdir }}/trainings/day-5/ansible.cfg
          ANSIBLE_LOG_PATH={{ logfile }}
          ansible-pull 
          -U {{ repo_url }} 
          -C {{ repo_branch }} 
          -d {{ workdir }} 
          {{ playbook }} >/dev/null 2>&1
        user: "{{ cron_user }}"

    - name: Create logrotate entry for ansible-pull.log
      template: 
        src: templates/etc_logrotate.d_ansible-pull.j2
        dest: /etc/logrotate.d/ansible-pull
        owner: "{{ cron_user }}"
        group: "{{ cron_group }}"
        mode: 0644
