- hosts: all
  gather_facts: no

  tasks:
  - raw: yum install -y sudo which
    args:
      creates: /bin/sudo
    register: yum_install
    changed_when: "'Nothing to do' not in yum_install.stdout"
    when: ansible_connection == 'docker'

- hosts: all
  become: yes

  vars:
    # schedule is fed directly to cron
    # schedule: '* * * * *'

    # User to run ansible-pull as from cron
    cron_user: root

    # File that ansible will use for logs
    logfile: /var/log/ansible-pull.log

    # Directory to where repository will be cloned
    workdir: /var/lib/ansible/local

    # Repository to check out -- YOU MUST CHANGE THIS
    # repo must contain a local.yml file at top level
    repo_url: git://github.com/sbeliakou/ansible-examples.git
    repo_branch: "training/ansible-11"

    playbook: "trainings/day-5/tasks/pull/local.yml"

  tasks:
    - name: install yum-utils
      yum: name=yum-utils

    - name: Install Cron
      yum: name=cronie

    - name: Ensure Cron Daemon is Running
      systemd: name=crond state=started

    - name: install epel
      yum: name=epel-release

    - name: install git
      yum: name=git

    - name: install python-pip
      yum: name=python-pip

    - name: Install ansible
      pip: name=ansible

    - name: Create local directory to work from
      file:
        path: "{{ workdir }}"
        state: directory
        owner: root
        group: root
        mode: 0751

    - name: Create Ansible Pull Cron Job
      cron:
        name: "Ansible Pull Job"
        job: >-
          PYTHONUNBUFFERED=1
          ANSIBLE_CONFIG={{ workdir }}/trainings/day-5/ansible.cfg
          ANSIBLE_LOG_PATH={{ logfile }}
          ansible-pull
          -U {{ repo_url }}
          -C {{ repo_branch }}
          -d {{ workdir }}
          --only-if-changed
          {{ playbook }} > /dev/null
        user: "{{ cron_user }}"

    - name: Create logrotate entry for ansible-pull.log
      template:
        src: templates/etc_logrotate.d_ansible-pull.j2
        dest: /etc/logrotate.d/ansible-pull
        owner: root
        group: root
        mode: 0644
